

- name: Deploy To tomcat
 hosts: web
 become: yes
 tasks:
  - name: Copy WAR file to tomcat
   copy:
    src: /var/snap/jenkins/5022/workspace/Ansibleapp/target/Ansibleapp.war
    dest: /opt/tomcat/webapps/Ansibleapp.war
    remote_src: no
  - name: Restart Tomcat
   shell: |
    /opt/tomcat/bin/shutdown.sh || true
    sleep 5
    /opt/tomcat/bin/startup.sh 
